apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: gcr.io/devops-pipeline-demo/demo-app
  newTag: latest

configMapGenerator:
- name: example-redis-config
  files:
  - redis-config

resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- ingress.yaml
- redis.yaml