apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: demo-app
  newName: gcr.io/devops-pipeline-demo/demo-app
  newTag: latest

resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- ingress.yaml