apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  env: develop

patchesStrategicMerge:
- ingress-host.yaml

commonAnnotations:
  support: support@doit-intl.com

namespace: demo-app-review

nameSuffix: -review

images:
- name: gcr.io/devops-pipeline-demo/demo-app
  newTag: v1v1
